#version: '3.8'

services:
  server:
    build: ./server
    container_name: portfolio-api-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      # Mount the persistent volume to the correct path inside the container
      - server_uploads:/app/uploads
    environment:
      - API_SERVER_URL=${API_SERVER_URL}
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=password
      - DB_NAME=portfolio_db
      - DB_PORT=5432
      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    container_name: portfolio-web-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - server

  db:
    image: postgres:15-alpine
    container_name: portfolio-postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=portfolio_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d portfolio_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  server_uploads:
